apiVersion: v1
kind: Namespace
metadata:
  name: ml-platform
  labels:
    name: ml-platform
    istio-injection: enabled # Enable Istio/KNative sidecar injection if using KServe with Istio
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
  labels:
    name: kserve
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  labels:
    name: team-a
    tenant: team-a
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  labels:
    name: team-b
    tenant: team-b
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-c
  labels:
    name: team-c
    tenant: team-c
    istio-injection: enabled
