apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-ai-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/enterprise/kubernetes-ai-infrastructure-platform.git'
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
