apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/enterprise/kubernetes-ai-infrastructure-platform.git'
    targetRevision: HEAD
    path: fastapi-platform-api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ml-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
