apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
data:
  ingress: |
    {
      "ingressGateway": "knative-ingress-gateway",
      "ingressService": "istio-ingressgateway.istio-system.svc.cluster.local",
      "ingressDomain": "ai-platform.enterprise.internal",
      "ingressClassName": "nginx"
    }
  explainers: |
    {
      "alibi": {
        "image": "docker.io/a12d/alibi:0.4.0"
      }
    }
  carves: |
    {
      "storage-initializer": {
        "image": "kserve/storage-initializer:v0.11.0"
      }
    }
